
import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { User, Channel, Company } from '../types';
import { api } from '../supabaseAPI';
import { shareFile } from '../capacitorUtils';
import { Modal } from './Modal';

interface DocumentShareModalProps {
    currentUser: User;
    company:     Company;
    docType:     'DC' | 'SALES_INVOICE';
    docData:     any;
    pdfBase64:   string; // Already generated by DocumentEngine
    onClose:     () => void;
}

export const DocumentShareModal: React.FC<DocumentShareModalProps> = ({ 
    currentUser, 
    company,
    docType, 
    docData, 
    pdfBase64,
    onClose 
}) => {
    const [step, setStep] = useState<'MODE' | 'PICK_GROUP'>('MODE');
    const [sharing, setSharing] = useState(false);
    const [selectedChannelIds, setSelectedChannelIds] = useState<Set<string>>(new Set());

    const docNumber = docData.dc_number || docData.invoice_number;
    const fileName = `${docType}_${docNumber}.pdf`;
    const docTitle = docType === 'DC' ? 'Delivery Challan' : 'Sales Invoice';

    // Queries
    const { data: channels = [], isLoading: loadingChannels } = useQuery<Channel[]>({
        queryKey: ['all_channels', currentUser.id],
        queryFn: () => api.getAllChannels(currentUser),
        enabled: step === 'PICK_GROUP'
    });

    // Data processing (Mirroring KramizSharePopup logic)
    const [searchQuery, setSearchQuery] = useState('');

    const filteredChannels = useMemo(() => {
        if (!searchQuery.trim()) return channels;
        const q = searchQuery.toLowerCase();
        return channels.filter(ch => {
            const order = (ch as any).order || null; // Some channels might have order pre-fetched or need lookup
            // If order not in ch, we should have fetched it in the query
            return (
                ch.name.toLowerCase().includes(q) ||
                order?.order_number?.toLowerCase().includes(q)
            );
        });
    }, [channels, searchQuery]);

    const groupedChannels = useMemo(() => {
        const groups: Record<string, { order: any; channels: Channel[] }> = {};
        filteredChannels.forEach(ch => {
            const order = (ch as any).order || null;
            const key = order ? order.id : 'General';
            if (!groups[key]) groups[key] = { order, channels: [] };
            groups[key].channels.push(ch);
        });
        return Object.values(groups).sort((a, b) => {
            if (!a.order) return 1;
            if (!b.order) return -1;
            return (b.order.created_at || '').localeCompare(a.order.created_at || '');
        });
    }, [filteredChannels]);

    const handleExternalShare = async () => {
        setSharing(true);
        try {
            await shareFile(fileName, pdfBase64, `Share ${docTitle}`);
            onClose();
        } catch (err: any) {
            alert(err.message);
        } finally {
            setSharing(false);
        }
    };

    const handleSendToGroups = async () => {
        if (selectedChannelIds.size === 0) return;
        setSharing(true);
        try {
            const byteCharacters = atob(pdfBase64);
            const byteNumbers = new Array(byteCharacters.length);
            for (let i = 0; i < byteCharacters.length; i++) {
                byteNumbers[i] = byteCharacters.charCodeAt(i);
            }
            const byteArray = new Uint8Array(byteNumbers);
            const blob = new Blob([byteArray], { type: 'application/pdf' });
            const file = new File([blob], fileName, { type: 'application/pdf' });

            const publicUrl = await api.uploadFile(file);

            const targets = Array.from(selectedChannelIds);
            await Promise.all(targets.map(channelId => 
                api.sendMessage(currentUser, channelId, `[FILE] ${publicUrl} | ${fileName}`)
            ));
            
            alert(`Sent to ${targets.length} groups!`);
            onClose();
        } catch (err: any) {
            alert('Failed to send to groups: ' + err.message);
        } finally {
            setSharing(false);
        }
    };

    return (
        <Modal isOpen={true} onClose={onClose} title={`Send ${docTitle}`}>
            {step === 'MODE' ? (
                <div className="space-y-3 py-2">
                    <p className="text-sm text-gray-500 mb-6">How would you like to share this document?</p>
                    
                    <button 
                        onClick={handleExternalShare}
                        disabled={sharing}
                        className="w-full flex items-center gap-4 p-4 bg-white border-2 border-gray-100 rounded-2xl hover:border-blue-200 hover:bg-blue-50/30 transition-all text-left group"
                    >
                        <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                            📤
                        </div>
                        <div className="flex-1">
                            <span className="block text-[15px] font-black text-gray-800">Share</span>
                            <span className="block text-[11px] text-gray-400 font-bold uppercase tracking-wider">WhatsApp, Email, etc.</span>
                        </div>
                    </button>

                    <button 
                        onClick={() => setStep('PICK_GROUP')}
                        disabled={sharing}
                        className="w-full flex items-center gap-4 p-4 bg-white border-2 border-gray-100 rounded-2xl hover:border-[#008069]/20 hover:bg-[#f0f9f7] transition-all text-left group"
                    >
                        <div className="w-12 h-12 bg-[#e7f3f1] text-[#008069] rounded-xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                            💬
                        </div>
                        <div className="flex-1">
                            <span className="block text-[15px] font-black text-gray-800">Send to the group</span>
                            <span className="block text-[11px] text-gray-400 font-bold uppercase tracking-wider">Share within Kramiz</span>
                        </div>
                    </button>
                    
                    <div className="pt-4 flex justify-end">
                        <button onClick={onClose} className="px-6 py-2 text-sm font-black text-gray-400 hover:text-gray-600 uppercase tracking-widest">
                            Cancel
                        </button>
                    </div>
                </div>
            ) : (
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <p className="text-sm text-gray-500 font-medium">Select groups ({selectedChannelIds.size})</p>
                        <button onClick={() => setStep('MODE')} className="text-xs font-black text-[#008069] uppercase tracking-widest">Back</button>
                    </div>

                    <div className="relative">
                        <input
                            type="text"
                            placeholder="Search groups or order #..."
                            value={searchQuery}
                            onChange={e => setSearchQuery(e.target.value)}
                            className="w-full bg-gray-50 border border-gray-200 rounded-2xl py-3 pl-10 pr-4 text-sm focus:ring-2 focus:ring-[#008069] outline-none transition-all"
                        />
                        <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400">🔍</span>
                    </div>

                    <div className="max-h-[350px] overflow-y-auto space-y-6 pr-1 minimal-scrollbar pb-2">
                        {loadingChannels ? (
                            <div className="py-10 text-center text-gray-400 animate-pulse font-bold">Fetching groups...</div>
                        ) : groupedChannels.length === 0 ? (
                            <div className="py-10 text-center text-gray-400 text-sm italic">No matching groups found.</div>
                        ) : (
                            groupedChannels.map(({ order, channels: orderChannels }) => (
                                <div key={order?.id || 'general'} className="space-y-2">
                                    <div className="flex items-center gap-2 px-1">
                                        <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                                            {order ? `Order ${order.order_number}` : 'General Groups'}
                                        </span>
                                        {order?.style_number && (
                                            <span className="text-[10px] font-bold text-gray-300">({order.style_number})</span>
                                        )}
                                    </div>
                                    <div className="grid grid-cols-1 gap-2">
                                        {orderChannels.map(ch => (
                                            <button 
                                                key={ch.id}
                                                onClick={() => {
                                                    const next = new Set(selectedChannelIds);
                                                    if (next.has(ch.id)) next.delete(ch.id); else next.add(ch.id);
                                                    setSelectedChannelIds(next);
                                                }}
                                                disabled={sharing}
                                                className={`w-full flex items-center gap-3 p-3.5 border rounded-2xl transition-all text-left shadow-sm ${selectedChannelIds.has(ch.id) ? 'bg-green-50 border-green-200 ring-1 ring-green-100' : 'bg-white border-gray-100 hover:bg-gray-50'}`}
                                            >
                                                <div className={`w-9 h-9 rounded-xl flex items-center justify-center font-black text-xs transition-colors ${selectedChannelIds.has(ch.id) ? 'bg-[#008069] text-white' : 'bg-gray-100 text-gray-400'}`}>
                                                    {ch.name[0].toUpperCase()}
                                                </div>
                                                <div className="flex-1 min-w-0">
                                                    <p className={`text-sm font-bold truncate ${selectedChannelIds.has(ch.id) ? 'text-[#008069]' : 'text-gray-800'}`}>{ch.name}</p>
                                                    <p className="text-[9px] text-gray-400 uppercase font-black tracking-tighter mt-0.5 opacity-60">Group Channel</p>
                                                </div>
                                                {selectedChannelIds.has(ch.id) && (
                                                    <div className="h-6 w-6 bg-[#008069] rounded-full flex items-center justify-center text-white text-[10px] font-black shadow-sm">✓</div>
                                                )}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            ))
                        )}
                    </div>

                    <button 
                        onClick={handleSendToGroups}
                        disabled={selectedChannelIds.size === 0 || sharing}
                        className="w-full py-4 bg-[#008069] text-white font-black text-sm uppercase tracking-widest rounded-2xl shadow-lg hover:bg-[#006a57] disabled:opacity-50 transition-all active:scale-95 flex items-center justify-center gap-2 mt-2"
                    >
                        {sharing ? 'Sending Document...' : `Send to ${selectedChannelIds.size} Groups`}
                    </button>
                </div>
            )}
        </Modal>
    );
};
